pipeline {
    agent any{

        docker {
            image 'snakee/golang-junit:1.21'
            reuseNode true
        }
    }
    stages {
        stage('unit tests - backend') {
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }
    }
}