pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            environment {
                GOCACHE = "/tmp/go-cache"
            }
            steps {
                sh 'mkdir -p /tmp/go-cache'
                dir('bugtracker-backend') {
                    sh '''
                        docker run --rm -v $PWD:/app -w /app snakee/golang-junit:1.21 \
                        sh -c "go test -v ./... 2>&1 | go-junit-report > test-results.xml"
                    '''
                }
            }
            post {
                always {
                    junit 'bugtracker-backend/test-results.xml'
                }
            }
        }

        stage('Unit Tests - Frontend') {
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                        docker run --rm -v $PWD:/app -w /app node:20-alpine sh -c "npm ci && npm test -- --reporter junit --reporter-options mochaFile=test-results.xml"
                    '''
                }
            }
            post {
                always {
                    junit 'bugtracker-frontend/test-results.xml'
                }
            }
        }
    }
}
